# 服务端口号
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: syb951007
    driver-class-name: com.mysql.cj.jdbc.Driver

  # rabbitmq 配置
  rabbitmq:
    host: 127.0.0.1
    name: guest
    password: guest
    port: 5672
    publisher-confirms: true
    publisher-returns: true
  #    listener:
  #      simple:
  #        #开启手动确定
  #        acknowledge-mode: manual
  #        # 是否支持重试
  #        retry:
  #          enabled: true


  # MQTT配置信息  发布
  mqtt:
    # MQTT服务地址，端口号默认11883，如果有多个，用逗号隔开
    url: tcp://127.0.0.1:1883
    # 用户名
    username: admin
    # 密码
    password: public
    # 客户端id(不能重复)
    client:
      id: provider-id
    # MQTT默认的消息推送主题，实际可在调用接口是指定
    default:
      topic: topic1

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: syb951007
    lettuce:
      pool:
        max-active: 8
        max-wait: 100ms
        max-idle: 8
        min-idle: 0
    database: 0



