# 服务端口号
server:
  port: 8080
#  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: syb951007
    driver-class-name: com.mysql.cj.jdbc.Driver

  # rabbitmq 配置
  rabbitmq:
    host: 127.0.0.1
    name: guest
    password: guest
    port: 5672
    publisher-confirms: true
    publisher-returns: true
  #    listener:
  #      simple:
  #        #开启手动确定
  #        acknowledge-mode: manual
  #        # 是否支持重试
  #        retry:
  #          enabled: true


  # MQTT配置信息  发布
  mqtt:
    # MQTT服务地址，端口号默认11883，如果有多个，用逗号隔开
    url: tcp://127.0.0.1:1883
    # 用户名
    username: admin
    # 密码
    password: public
    # 客户端id(不能重复)
    client:
      id: provider-id
    # MQTT默认的消息推送主题，实际可在调用接口是指定
    default:
      topic: topic1

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: syb951007
    lettuce:
      pool:
        max-active: 8
        max-wait: 100ms
        max-idle: 8
        min-idle: 0
    database: 0

#kafka
  kafka: # 指定kafka 代理地址，可以多个
    bootstrap-servers: http://localhost:9092
    consumer: # 指定默认消费者group id
      group-id: myGroup
    template: # 指定默认topic id
      default-topic: tsc_dsc_newMsg
    listener: # 指定listener 容器中的线程数，用于提高并发量
      concurrency: 5
    producer: # 每次批量发送消息的数量
      batch-size: 1000

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: provider-group


weixin:
  appId: wx15a027e325d0ed8b
  secret: 63c3e84401a09f526d026077ce159ed2

weixingzh:
#  appId: wxfc97369dec7affae
#  secret: 3ae9dad55e54029694c78be4b10c86f5
  appId: wxda2b2ff6fadeadd2
  secret: b33fb975fab25cbdbf2ad381c8f3b631
# token配置
token:
  # token 值
  value: syb951007
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: 5aKm2rcGIVaOMLPy9ZdThklBUV4DD7iTucDCVVa6pu5
  # 令牌有效期（默认30分钟）
  expireTime: 30




